# Generated by Django 3.1.4 on 2021-01-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(db_index=True, max_length=64)),
                ('magic_power', models.CharField(choices=[('Obrazenia od ognia', 'Fire Damage'), ('Obrazenia od magii', 'Magic Damage')], max_length=96)),
                ('artifact_type', models.CharField(choices=[('bron', 'Weapon'), ('zbroja', 'Armor'), ('bizuteria', 'Jewelry')], max_length=96)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField(null=True)),
                ('toughness', models.CharField(choices=[('Latwy', 'Easy'), ('Sredni', 'Medium'), ('Trudny', 'Hard'), ('Bardzo trudny', 'Ultra Hard'), ('Ekstremalnie ciezki', 'Extreme')], max_length=32)),
                ('land', models.CharField(choices=[('Tilea', 'Tilea'), ('Imperium', 'Empire'), ('Gory Kranca Swiata', 'We Mountains'), ('Gory Szare', 'Grey Mountains'), ('Bretonia', 'Bretonny')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(null=True)),
                ('number_of_pieces', models.PositiveIntegerField(default=1)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.enemy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.keydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.artifactdefinition')),
            ],
        ),
    ]
