# Generated by Django 3.1.4 on 2021-01-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210107_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='land',
            field=models.CharField(choices=[('TILEA', 'Tilea'), ('EMPIRE', 'Imperium'), ('WE_MOUNTAINS', 'Gory Kranca Swiata'), ('GREY_MOUNTAINS', 'Gory Szare'), ('BRETONIA', 'Bretonia')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='toughness',
            field=models.CharField(choices=[('EASY', 'Latwy'), ('MEDIUM', 'Sredni'), ('HARD', 'Trudny'), ('ULTRA_HARD', 'Bardzo trudny'), ('EXTREME', 'Ekstremalnie ciezki')], max_length=32),
        ),
    ]
